// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUxOL2DneRrwYkzu19_GCGyCkEpPvIfVs',
    appId: '1:1042290834058:android:40e4ca6990d0e498cacb73',
    messagingSenderId: '1042290834058',
    projectId: 'quadconnect-65159',
    storageBucket: 'quadconnect-65159.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCst8z4uFe-85toJTd_ElntDlsYAFdznCE',
    appId: '1:1042290834058:ios:fe477fce29ec7eedcacb73',
    messagingSenderId: '1042290834058',
    projectId: 'quadconnect-65159',
    storageBucket: 'quadconnect-65159.firebasestorage.app',
    iosBundleId: 'com.quadconnect.quadcnct',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYNvsIKLOFUJxvmGJMiWgmiF2CFNOAuSk',
    appId: '1:511791365520:web:8c7b6f3c6801853c258715',
    messagingSenderId: '511791365520',
    projectId: 'quadcnct',
    authDomain: 'quadcnct.firebaseapp.com',
    storageBucket: 'quadcnct.firebasestorage.app',
  );

}